### PR TITLE
Revised data

### PR DESCRIPTION
**Pull request by jwildfire**
Adding first draft of revised test data. Will look more closely in the next few days and start to think about needed updates to support this data structure. 

@MayaGans feel free to dig in as your time allows.

### CODE REVIEW

**Comment by MayaGans** [comment]
First stab trying to make sense of this and how we'd need to manipulate the data to fit our current plots and I'm not sure where you get any of the values to make the diamonds from this. Looks like we might be able to extract the group graph values though? 

| CSV | JSON | NOTES | 
| ---- | --- | --- |
| "" | NO ROW NUMBER |
| "AEDECOD" | SOC? |
| "AEBODSYS" | TERM? |
| Group1 | NOT IN JSON, USED AS DATA PREFIX |
| Group2 | NOT IN JSON, USED AS DATA PREFIX |
| n1 | Group1_n | use Group1 value to rename Xan_Hi_n
| n2 | Group2_n | use Group2 value to rename Pbo_n
| N1 | Group1_nn | use Group1 value to rename Xan_Hi_nn
| N2 | Group2_nn | use Group2 value to rename Pbo_nn
| Test | Not in JSON |
| Res | Maybe or? | we need 2 of these for both Xan_Hi_or and Pbo_or
| Pval | pval |
| CI_Lower | | we need 2 of these for both Xan_Hi_or and Pbo_or
| Ci_Upper | | we need 2 of these for both Xan_Hi_or and Pbo_or

How do we get percent and total for the group graphs? How do we even begin to make the diamonds?

```
    chart.raw.forEach(function(d){
        d.groups = groups.map(function(group){
            return { 
                key:group,
                percent:d[group+"_percent"], // doesnt exist
                n: d[group + "_n"], 
                total: d[group+"_total"] // doesnt exist (can we just make this/ calculate based on both ns?) 
            }
        })
        d.pairs = pairs.map(function (pair) { 
            let pair_id = pair[0] + "_" + pair[1] 
            return { 
                key: pair_id, 
                group1:pair[0],
                group2:pair[1],
                label:pair[0]+" vs. "+pair[1],
                or: d[pair_id + "_or"], // what is or here?
                p: d[pair_id+ "_pval"]
            }
        })
    })
```

**Comment by jwildfire** [comment]
Simplest thing is probably to have a data processing step where we convert the .csv to one record per SOC/PT (instead of one record per test). Can do most of it with d3.nest(). I'll get a PR started this week and then we can chat.

**Comment by jwildfire** [comment]
OK - added the function to process/nest the data. Output (see below) should be pretty similar to what we had now.

image

I'll work on getting the chart to draw next. Or feel free to take a shot if you've got time and are feeling motivated. I probably won't get back to it until Tues or Weds at the earliest.

**Comment by jwildfire** [comment]
OK - it's definitely not super clean, but other than the few issues I've filed. It's working. Take a look when you get a chance and maybe we can chat later this week.

**Comment by MayaGans** [comment]
This looks great! I'm not familiar with the `factory` call but I think I'm getting the general idea of how you broke this up. I realize you're super busy but I'd love a walkthrough if you have some time just to confirm my mental model! As for merging this, it looks like we have some conflicts and there's a bunch of `console.log` statements we might consider removing? Also we get a ton of errors for what I'm assuming is d3 trying to draw a path for null data points? Regardless super neat to see how you got the data in the right format

**Review by MayaGans — APPROVED** [review]
LGTM!

**Pull request merged**
