### PR TITLE
7 CI

### PR DESCRIPTION
**Pull request by MayaGans**
# Added a line in black and some dummy data for 4 observations

Screen Shot 2020-11-05 at 10 53 18 AM

This will assume that each pair type has an observation called `ci_high` and `ci_low` [I just made these up]

```
{
	"soc": "Blood and lymphatic system disorders",
	"term": "Iron deficiency anaemia",
	"pbo_total": 232,
	"low_total": 267,
	"high_total": 278,
	"pbo_n": 4,
	"low_n": 7,
	"high_n": 0,
	"pbo_nn": 228,
	"low_nn": 260,
	"high_nn": 278,
	"pbo_percent": 1.72,
	"low_percent": 2.62,
	"high_percent": 0.0,
	"total_n": 11,
	"total_percent": 1.42,
	"low_pbo_or": 1.5088,
	"low_pbo_pval": 0.5192,
	"high_pbo_or": null,
	"high_pbo_pval": null,
	"high_pbo_ci_high": null,
	"high_pbo_ci_low": null,
	"low_pbo_ci_high": 0,
	"low_pbo_ci_low": 1
}
```

### CODE REVIEW

**Comment by MayaGans** [comment]
```
        diffPoints.append("g")
            .selectAll("myline")
            // does this do what I think it does?
            .data(d=>d.pairs)
            .join("line")
            // not quite sure what these should be honestly
            .attr("x1", d => orScale(d.ci_high))
            .attr("x2", d => orScale(d.ci_low))
            .attr("y1", function (d) { return d.y; })
            .attr("y2", function (d) { return d.y; })
            .attr("stroke", "#0015BC")
            .attr("stroke-width", "1px")
            .style("opacity", 0.6);
```

**Comment by MayaGans** [comment]
THIS WORKS: https://observablehq.com/@mayagans/offset-vertically

**Comment by MayaGans** [comment]
This will close #7 🥳

**Comment by MayaGans** [comment]
I thought the black was a little jarring so I bumped down the opacity 

Screen Shot 2020-11-05 at 11 15 03 AM

**Review by jwildfire — APPROVED** [review]
Looks great.

**Pull request merged**
